layout first screen and add navigation
david-storm/android_lesson_01 pull request #1
Opened 2021-04-11 13:34 UTC by david-storm

2021-04-12 08:49 UTC, onix-roman requested changes

2021-04-12 08:49 UTC, onix-roman commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
Удали ненужную зависимость

2021-04-12 09:50 UTC, VladimirOnix approved these changes
Take a look in comments

2021-04-12 17:35 UTC, david-storm commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
+

2021-04-12 17:36 UTC, david-storm commented on app/build.gradle
> +    implementation 'androidx.legacy:legacy-support-v4:1.0.0'
+

2021-04-13 14:04 UTC, onix-roman approved these changes

2021-04-13 14:06 UTC, merged